"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Dividers = exports.ColorName = exports.AnimatableManager = exports.ThemeManager = exports.Components = exports.ComponentsColors = exports.Spacings = exports.Shadows = exports.BorderRadiuses = exports.Typography = exports.Colors = void 0;
var colors_1 = require("./colors");
Object.defineProperty(exports, "Colors", { enumerable: true, get: function () { return __importDefault(colors_1).default; } });
var typography_1 = require("./typography");
Object.defineProperty(exports, "Typography", { enumerable: true, get: function () { return __importDefault(typography_1).default; } });
var borderRadiuses_1 = require("./borderRadiuses");
Object.defineProperty(exports, "BorderRadiuses", { enumerable: true, get: function () { return __importDefault(borderRadiuses_1).default; } });
var shadows_1 = require("./shadows");
Object.defineProperty(exports, "Shadows", { enumerable: true, get: function () { return __importDefault(shadows_1).default; } });
var spacings_1 = require("./spacings");
Object.defineProperty(exports, "Spacings", { enumerable: true, get: function () { return __importDefault(spacings_1).default; } });
var componentsColors_1 = require("./componentsColors");
Object.defineProperty(exports, "ComponentsColors", { enumerable: true, get: function () { return __importDefault(componentsColors_1).default; } });
var components_1 = require("./components");
Object.defineProperty(exports, "Components", { enumerable: true, get: function () { return __importDefault(components_1).default; } });
var themeManager_1 = require("./themeManager");
Object.defineProperty(exports, "ThemeManager", { enumerable: true, get: function () { return __importDefault(themeManager_1).default; } });
var animatableManager_1 = require("./animatableManager");
Object.defineProperty(exports, "AnimatableManager", { enumerable: true, get: function () { return __importDefault(animatableManager_1).default; } });
var colorName_1 = require("./colorName");
Object.defineProperty(exports, "ColorName", { enumerable: true, get: function () { return __importDefault(colorName_1).default; } });
var dividers_1 = require("./dividers");
Object.defineProperty(exports, "Dividers", { enumerable: true, get: function () { return __importDefault(dividers_1).default; } });
